"""
Optional Python sidecar for heavier media / diffusion workflows.
This default implementation returns a generated SVG data URI for image requests
so media rendering works end-to-end without external providers.
"""

from urllib.parse import quote
from fastapi import FastAPI
from pydantic import BaseModel, Field

app = FastAPI(title="Persona Media Worker", version="0.1.0")


class ImageRequest(BaseModel):
    prompt: str = Field(..., min_length=1, max_length=4000)
    persona_slug: str | None = None


class VideoRequest(BaseModel):
    prompt: str = Field(..., min_length=1, max_length=4000)
    duration_sec: int | None = Field(default=5, ge=1, le=60)


@app.get("/health")
def health():
    return {"ok": True, "service": "persona-media-worker"}


@app.post("/v1/image")
def generate_image(req: ImageRequest):
    prompt = req.prompt.strip()
    persona = (req.persona_slug or "assistant").strip()
    safe_title = _short_line(f"{persona} image", 40)
    safe_prompt = _short_line(prompt, 120)
    svg = f"""<svg xmlns='http://www.w3.org/2000/svg' width='1024' height='1024' viewBox='0 0 1024 1024'>
<defs><linearGradient id='g' x1='0' y1='0' x2='1' y2='1'><stop stop-color='#5b21b6'/><stop offset='1' stop-color='#0ea5e9'/></linearGradient></defs>
<rect width='1024' height='1024' fill='url(#g)'/>
<rect x='56' y='56' width='912' height='912' rx='28' fill='rgba(0,0,0,0.45)' stroke='rgba(255,255,255,0.35)'/>
<text x='96' y='140' fill='white' font-size='42' font-family='Arial, sans-serif' font-weight='700'>{safe_title}</text>
<text x='96' y='200' fill='white' font-size='30' font-family='Arial, sans-serif'>{safe_prompt}</text>
<text x='96' y='946' fill='rgba(255,255,255,0.9)' font-size='24' font-family='Arial, sans-serif'>Generated by Persona Media Worker</text>
</svg>"""
    image_url = "data:image/svg+xml;utf8," + quote(svg)
    return {
        "status": "ok",
        "provider": "local-svg-placeholder",
        "prompt": prompt,
        "image_url": image_url,
        "message": "Image generated by local media worker placeholder provider.",
    }


@app.post("/v1/video")
def generate_video(req: VideoRequest):
    return {
        "status": "stub",
        "prompt": req.prompt,
        "duration_sec": req.duration_sec,
        "message": "Video generation provider is not enabled yet.",
    }


def _short_line(text: str, limit: int) -> str:
    compact = " ".join(text.split())
    if len(compact) <= limit:
        return compact
    return compact[: max(0, limit - 3)] + "..."
