"""
Optional Python sidecar for heavier media / diffusion workflows.
This default implementation returns a generated SVG data URI for image requests
so media rendering works end-to-end without external providers.
"""

import base64
import json
import os
import uuid
from pathlib import Path
from urllib.parse import quote
from fastapi import FastAPI
import httpx
from dotenv import load_dotenv
from pydantic import BaseModel, Field
from fastapi.staticfiles import StaticFiles

_ROOT = Path(__file__).resolve().parents[3]
load_dotenv(_ROOT / "services" / "media-worker" / ".env", override=False)
load_dotenv(_ROOT / "apps" / "api" / ".env", override=False)

app = FastAPI(title="Persona Media Worker", version="0.1.0")
MEDIA_DIR = Path(os.getenv("MEDIA_WORKER_STORAGE_DIR", "./generated-media")).resolve()
MEDIA_PUBLIC_BASE_URL = os.getenv("MEDIA_PUBLIC_BASE_URL", "").strip().rstrip("/")
OPENAI_API_KEY = os.getenv("OPENAI_API_KEY", "").strip()
OPENAI_BASE_URL = os.getenv("OPENAI_BASE_URL", "https://api.openai.com/v1").strip().rstrip("/")
OPENAI_IMAGE_MODEL = os.getenv("OPENAI_IMAGE_MODEL", "gpt-image-1").strip()
MEDIA_DIR.mkdir(parents=True, exist_ok=True)
app.mount("/media", StaticFiles(directory=str(MEDIA_DIR)), name="media")


class ImageRequest(BaseModel):
    prompt: str = Field(..., min_length=1, max_length=4000)
    persona_slug: str | None = None


class VideoRequest(BaseModel):
    prompt: str = Field(..., min_length=1, max_length=4000)
    duration_sec: int | None = Field(default=5, ge=1, le=60)


class UploadRequest(BaseModel):
    data_base64: str = Field(..., min_length=8, max_length=80_000_000)
    mime_type: str = Field(..., min_length=3, max_length=120)
    file_name: str | None = Field(default=None, max_length=200)
    persona_slug: str | None = Field(default=None, max_length=120)


@app.get("/health")
def health():
    return {
        "ok": True,
        "service": "persona-media-worker",
        "realImageProviderEnabled": bool(OPENAI_API_KEY),
        "imageModel": OPENAI_IMAGE_MODEL,
    }


@app.post("/v1/image")
def generate_image(req: ImageRequest):
    prompt = req.prompt.strip()
    persona = (req.persona_slug or "assistant").strip()
    if OPENAI_API_KEY:
        real, err = _generate_openai_image(prompt)
        if real:
            return {
                "status": "ok",
                "provider": "openai-images",
                "prompt": prompt,
                "image_url": real,
                "message": "Image generated by OpenAI image provider.",
            }
        if err:
            fallback_note = f"OpenAI image provider failed: {err}. Falling back to local placeholder."
        else:
            fallback_note = "OpenAI image provider unavailable. Falling back to local placeholder."
    else:
        fallback_note = "No OpenAI image provider configured. Using local placeholder."
    safe_title = _short_line(f"{persona} image", 40)
    safe_prompt = _short_line(prompt, 120)
    svg = f"""<svg xmlns='http://www.w3.org/2000/svg' width='1024' height='1024' viewBox='0 0 1024 1024'>
<defs><linearGradient id='g' x1='0' y1='0' x2='1' y2='1'><stop stop-color='#5b21b6'/><stop offset='1' stop-color='#0ea5e9'/></linearGradient></defs>
<rect width='1024' height='1024' fill='url(#g)'/>
<rect x='56' y='56' width='912' height='912' rx='28' fill='rgba(0,0,0,0.45)' stroke='rgba(255,255,255,0.35)'/>
<text x='96' y='140' fill='white' font-size='42' font-family='Arial, sans-serif' font-weight='700'>{safe_title}</text>
<text x='96' y='200' fill='white' font-size='30' font-family='Arial, sans-serif'>{safe_prompt}</text>
<text x='96' y='946' fill='rgba(255,255,255,0.9)' font-size='24' font-family='Arial, sans-serif'>Generated by Persona Media Worker</text>
</svg>"""
    image_url = "data:image/svg+xml;utf8," + quote(svg)
    return {
        "status": "ok",
        "provider": "local-svg-placeholder",
        "prompt": prompt,
        "image_url": image_url,
        "message": fallback_note,
    }


@app.post("/v1/video")
def generate_video(req: VideoRequest):
    placeholder_url = _make_local_placeholder_video(req.prompt)
    return {
        "status": "stub",
        "prompt": req.prompt,
        "duration_sec": req.duration_sec,
        "video_url": placeholder_url,
        "message": "Video generation provider is not enabled yet. Local placeholder preview attached.",
    }


@app.post("/v1/upload")
def upload_media(req: UploadRequest):
    mime = req.mime_type.strip().lower()
    if not (mime.startswith("image/") or mime.startswith("video/")):
        return {"status": "failed", "message": "Only image/video MIME types are supported."}
    try:
        binary = base64.b64decode(req.data_base64, validate=True)
    except Exception:
        return {"status": "failed", "message": "Invalid base64 payload."}
    if not binary:
        return {"status": "failed", "message": "Empty file payload."}
    ext = _ext_from_mime(mime)
    kind = "image" if mime.startswith("image/") else "video"
    file_id = uuid.uuid4().hex
    safe_name = (req.file_name or f"upload-{file_id}{ext}").replace("/", "_").replace("\\", "_")
    stored_name = f"{file_id}-{safe_name}"
    file_path = MEDIA_DIR / stored_name
    file_path.write_bytes(binary)
    url = _public_media_url(stored_name)
    return {
        "status": "ok",
        "kind": kind,
        "mime_type": mime,
        "file_name": req.file_name or safe_name,
        "url": url,
        "message": "Media uploaded successfully.",
    }


def _short_line(text: str, limit: int) -> str:
    compact = " ".join(text.split())
    if len(compact) <= limit:
        return compact
    return compact[: max(0, limit - 3)] + "..."


def _ext_from_mime(mime: str) -> str:
    table = {
        "image/jpeg": ".jpg",
        "image/png": ".png",
        "image/webp": ".webp",
        "image/gif": ".gif",
        "image/svg+xml": ".svg",
        "video/mp4": ".mp4",
        "video/webm": ".webm",
        "video/quicktime": ".mov",
    }
    return table.get(mime, ".bin")


def _public_media_url(stored_name: str) -> str:
    if MEDIA_PUBLIC_BASE_URL:
        return f"{MEDIA_PUBLIC_BASE_URL}/media/{stored_name}"
    return f"/media/{stored_name}"


def _make_local_placeholder_video(prompt: str) -> str:
    text = _short_line(prompt, 120)
    svg = f"""<svg xmlns='http://www.w3.org/2000/svg' width='1280' height='720' viewBox='0 0 1280 720'>
<defs><linearGradient id='g' x1='0' y1='0' x2='1' y2='1'><stop stop-color='#111827'/><stop offset='1' stop-color='#7c3aed'/></linearGradient></defs>
<rect width='1280' height='720' fill='url(#g)'/>
<rect x='60' y='60' width='1160' height='600' rx='24' fill='rgba(0,0,0,0.42)' stroke='rgba(255,255,255,0.25)'/>
<text x='100' y='150' fill='white' font-size='44' font-family='Arial, sans-serif' font-weight='700'>Video preview</text>
<text x='100' y='220' fill='rgba(255,255,255,0.92)' font-size='30' font-family='Arial, sans-serif'>{text}</text>
<polygon points='610,320 610,470 740,395' fill='rgba(255,255,255,0.92)'/>
</svg>"""
    return "data:image/svg+xml;utf8," + quote(svg)


def _generate_openai_image(prompt: str) -> tuple[str | None, str | None]:
    body = {
        "model": OPENAI_IMAGE_MODEL,
        "prompt": prompt,
        "size": "1024x1024",
    }
    headers = {
        "Authorization": f"Bearer {OPENAI_API_KEY}",
        "Content-Type": "application/json",
    }
    try:
        with httpx.Client(timeout=120.0) as client:
            res = client.post(f"{OPENAI_BASE_URL}/images/generations", json=body, headers=headers)
            res.raise_for_status()
            data = res.json()
        rows = data.get("data")
        if not isinstance(rows, list) or not rows:
            return None, "response missing data rows"
        first = rows[0]
        direct_url = first.get("url")
        if isinstance(direct_url, str) and direct_url.strip():
            return direct_url.strip(), None
        b64 = first.get("b64_json")
        if isinstance(b64, str) and b64.strip():
            image_bytes = base64.b64decode(b64)
            file_name = f"{uuid.uuid4().hex}-generated.png"
            (MEDIA_DIR / file_name).write_bytes(image_bytes)
            return _public_media_url(file_name), None
        return None, "response missing url and b64_json"
    except httpx.HTTPStatusError as e:
        detail = ""
        try:
            payload = e.response.json()
            detail = json.dumps(payload)
        except Exception:
            detail = e.response.text or ""
        detail = " ".join(detail.split())[:400]
        return None, f"HTTP {e.response.status_code}: {detail or str(e)}"
    except Exception as e:
        return None, str(e)
